---
title: Horizen Academy
timezone: America/New_York
email: info@horizen.global
description: Horizen Academy
baseurl: ""
url: https://academy.horizen.io
logo: /assets/img/Logo-beta.svg
author:
  name: Horizen Academy
  email: info@horizen.global
  uri: https://academy.horizen.io
  bio:
  facebook: https://www.facebook.com/horizenglobal/
  twitter: horizenglobal
  linkedin: https://www.linkedin.com/company/25052505/
  gplus:
  youtube: https://www.youtube.com/channel/UCQ0v_lUnZHIKUQUXJzfgqOg
links:
  bitcointalk: https://bitcointalk.org/index.php?topic=2047435.0
  blog: https://blog.horizen.global/
  facebook: https://www.facebook.com/horizenglobal/
  linkedin: https://www.linkedin.com/company/25052505/
  forum: https://forum.horizen.global/
  github: https://github.com/ZencashOfficial
  medium: https://medium.com/zencash
  reddit: https://www.reddit.com/r/Horizen/
  discord: https://horizen.global/invite/discord
  telegram: https://horizen.global/invite/telegram
  twitter: https://twitter.com/horizenglobal
  youtube: https://www.youtube.com/channel/UCQ0v_lUnZHIKUQUXJzfgqOg
  store: https://store.horizen.global/
  support: https://support.horizen.global
algolia:
  application_id: LAIP286P46
  search_only_api_key: 5ab28de7858bf585159b2d4f8272d060
  index_name: horizen_academy
future: true
permalink: pretty
excerpt_separator:
markdown: kramdown
plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin
exclude:
  - _dev
  - bower.json
  - .env.json
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor

languages: ["en", "es", "fr"]
exclude_from_localizations: ["assets"]
